nelmio_cors:
  defaults:
    allow_origin: ['https://localhost:3000', 'https://127.0.0.1:3000', 'https://localhost:3001', 'https://127.0.0.1:3001', 'https://localhost:3002', 'https://127.0.0.1:3002']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
    allow_credentials: true
  paths:
    '^/': ~


# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: []
#         allow_headers: []
#         allow_methods: []
#         expose_headers: []
#         max_age: 0
#     paths:
#         '^/api':
#             allow_credentials: false
#             allow_origin: ['http://localhost:3000', 'http://localhost:3000', 'https://127.0.0.1:8000']
#             allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
#             allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#             max_age: 3600
#     # '^/': null
