version: '3.8'

services:
  app:
    image: randre0/homecyclhome_api-app:latest
    container_name: homecyclhome_api_app
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: postgresql://postgres:ycoOCSg6QTKlfZoPRlMmPzlRxZRg5fWF@database:5432/homecyclhome?serverVersion=16&charset=utf8
      APP_SECRET: ${APP_SECRET}
      APP_TIMEZONE: ${APP_TIMEZONE}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - database
    env_file:
      - .env.prod

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: homecyclhome_api_database
    environment:
      POSTGRES_DB: homecyclhome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ycoOCSg6QTKlfZoPRlMmPzlRxZRg5fWF
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: andr.raphael@yahoo.fr
      PGADMIN_DEFAULT_PASSWORD: ycoOCSg6QTKlfZoPRlMmPzlRxZRg5fWF
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  database_data:
  caddy_data:
  caddy_config:
  pgdata:
